### ISSUE TITLE
localisation possible?

### ISSUE THREAD

**Issue by jotata** [TotallyInformation/node-red-contrib-moment#1]
Hello!
this is a great node for node-red!

Is ist possible, to integrate localisation for it, so that il get the output result in german?
If you use moment.locale("de").format('LLL') it shoud work (http://stackoverflow.com/questions/17493309/how-do-i-change-the-language-of-moment-js). It is also workin for the other functions.

Maybe you can add a field for locale in the node-settings? 

That would be great!
jotata

**Comment by TotallyInformation** [comment]
Hi jotata, great idea. I'm just back from holiday and have a backlog of work but I will note this for an enhancement unless you want to pull a change?

**Comment by Jacques44** [comment]
I've made this change to add localisation
I'll pull it right now

**Comment by TotallyInformation** [comment]
Cool. I'll have a look.

**Comment by TotallyInformation** [comment]
Hopefully Jacques' pull closes this. If not, just reopen.

**Comment by jotata** [comment]
Great Work!
I just tried it and it works fine! Thanks!

Freundliche Grüsse
J. Tanner

Am 30.03.2016 um 13:01 schrieb Jacques44:
