### ISSUE TITLE
set output timezone in msg-object

### ISSUE THREAD

**Issue by Rene-Auberger** [TotallyInformation/node-red-contrib-moment#10]
A possibility to set the output timezone for node-red-contrib-moment in the msg-object that is passed to the node would be very helpful in many situations.

**Comment by TotallyInformation** [comment]
Maybe allow msg.moment to be set with element names matching the internal config variables. Then allow those to override the config settings.

**Comment by TotallyInformation** [comment]
Going to close this as it has been open for a long time. However, it is now on my backlog for a future release.
