### ISSUE TITLE
'object' output showing 0-11 month rather than 1-12

### ISSUE THREAD

**Issue by ad84** [TotallyInformation/node-red-contrib-moment#11]
The month component of the 'object' output seems to run from 0-11 rather than 1-12. This is easily adjusted for and not a major issue, but is it the expected output?

**Comment by TotallyInformation** [comment]
No, that appears to be a bug. I'll try to track it down.

**Comment by TotallyInformation** [comment]
Actually it appears to be an upstream bug in moment.js - I'll have to raise it there - though I may put in a work-around.

**Comment by TotallyInformation** [comment]
Upstream issue raised: https://github.com/moment/moment/issues/3910

**Comment by TotallyInformation** [comment]
Grr, found this in the moment documentation under [Get](https://momentjs.com/docs/#/get-set/get/):

`moment().get('month');  // 0 to 11`

Which seems to imply that this is deliberate - though why is anyone's guess

And under set as well:

`moment().set('month', 3);  // April`

So it seems unlikely that moment.js will fix this. I'm kind of loath to change this here as it would mean that the output is inconsistent with moment.js and this has an impact on input objects too. I think I may have to wait to see what moment.js says. In the meantime, I'll update the documentation anyway.
