### ISSUE TITLE
Moment node does not accept blank string input

### ISSUE THREAD

**Issue by drmibell** [TotallyInformation/node-red-contrib-moment#14]
The new release (2.0.6) resolves the issue with timestamp input (#13), but a blank string throws the error:
"The input property was NOT a recognisable date. Output will be a blank string."
According to the readme,
"If the input is null, does not exist or is a blank string, the current Date/Time will be used."

**Comment by TotallyInformation** [comment]
Can I just check - is it throwing an error or is it outputting a warning msg? It should be showing a warning in the debug panel to indicate that a blank string input is probably not what you want to be sending.

**Comment by mikeS7** [comment]
Yes, it's a warning, but according to readme current timestamp should be set as output.
I've got blank string as mentioned in the warning. So warning or readme should be corrected

**Comment by drmibell** [comment]
As mikeS7 says, it is a warning, not an error. The readme seems partially correct. If the input is undefined (e.g., read from msg.foo), the output is the current timestamp, correctly formatted. If the input is null or a blank string, I get the warning.

**Comment by TotallyInformation** [comment]
OK, thanks for reporting. I will update for the next release.

**Comment by drmibell** [comment]
Since this issue is still open, I want to object (respectfully) that the issue is not simply one of documentation. According to the node help:

> If the input is null, does not exist or is a blank string, the current Date/Time will be used.

Consider these two flows:
`[{"id":"1702db0f.28f565","type":"moment","z":"2a71f2d4.276f46","name":"input: msg.payload","topic":"","input":"","inputType":"msg","inTz":"America/New_York","adjAmount":0,"adjType":"days","adjDir":"add","format":"YYYY-MM-DD HH:mm","locale":"en_US","output":"now","outputType":"msg","outTz":"America/New_York","x":350,"y":100,"wires":[["12b62249.76f40e"]]},{"id":"a313089a.d46c8","type":"inject","z":"2a71f2d4.276f46","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":120,"y":40,"wires":[["1702db0f.28f565"]]},{"id":"12b62249.76f40e","type":"debug","z":"2a71f2d4.276f46","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":530,"y":100,"wires":[]},{"id":"9dbd9c70.ae8958","type":"inject","z":"2a71f2d4.276f46","name":"blank string","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":"","x":110,"y":80,"wires":[["1702db0f.28f565"]]},{"id":"6d965202.635574","type":"inject","z":"2a71f2d4.276f46","name":"'test'","topic":"","payload":"test","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":"","x":130,"y":120,"wires":[["1702db0f.28f565"]]},{"id":"83ade918.7f41a8","type":"inject","z":"2a71f2d4.276f46","name":"null","topic":"","payload":"null","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":"","x":130,"y":160,"wires":[["1702db0f.28f565"]]},{"id":"6efade01.329738","type":"moment","z":"2a71f2d4.276f46","name":"input: msg.foo","topic":"","input":"foo","inputType":"msg","inTz":"America/New_York","adjAmount":0,"adjType":"days","adjDir":"add","format":"YYYY-MM-DD HH:mm","locale":"en_US","output":"now","outputType":"msg","outTz":"America/New_York","x":340,"y":280,"wires":[["8eafe17a.580a"]]},{"id":"7381a9ba.ac97d","type":"inject","z":"2a71f2d4.276f46","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":120,"y":220,"wires":[["6efade01.329738"]]},{"id":"8eafe17a.580a","type":"debug","z":"2a71f2d4.276f46","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":530,"y":280,"wires":[]},{"id":"ffd52fb2.aa5978","type":"inject","z":"2a71f2d4.276f46","name":"blank string","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":"","x":110,"y":260,"wires":[["6efade01.329738"]]},{"id":"c023582b.44ed78","type":"inject","z":"2a71f2d4.276f46","name":"'test'","topic":"","payload":"test","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":"","x":130,"y":300,"wires":[["6efade01.329738"]]},{"id":"74aca578.d2450c","type":"inject","z":"2a71f2d4.276f46","name":"null","topic":"","payload":"null","payloadType":"json","repeat":"","crontab":"","once":false,"onceDelay":"","x":130,"y":340,"wires":[["6efade01.329738"]]}]`

In the first flow, the moment node gets input on msg.payload. In this case, 
- timestamp gives the correct output
- blank string gives a warning message and an empty string on output
- 'test' string gives a warning message and and an empty string on output
- null gives an incorrect time (1969-12-31 19:00)

In the second flow, input on msg.foo (nonexistent message property) gives the current date and time in each case.

According to the documentation (and to make the node as useful as possible), each case except the timestamp should give the same result -- the current date/time. This may be partly the result of my system (moment.js has its quirks), but I am using the current Raspbian on a Pi 3.

**Comment by TotallyInformation** [comment]
Respectful objections always welcome here! ;)

Thanks for digging into this. I am happy to improve the code. I'd be even happier if you were to submit a Pull Request! As I'm tied up on other projects at the moment and I'm not really getting any time to look at Node-RED.

**Comment by TotallyInformation** [comment]
As I have to update this for an upstream dependency, looking at it again.

The outputs are as expected here except for null. When you set the output to something other than payload, the original payload is preserved which I think is correct. 

The output is an empty string if the input is not a date/time, possibly not the best choice in hindsight but that's the way it is. Changing that at this point would be breaking for anyone who is relying on that output.

So the exception is the output being incorrect when `null` is the input. That is a bug it seems to me, it should output the same as any other unrecognised input. 

I've also asked in the Discourse group as to whether people would prefer to change the default output. If there is a consensus, I will attempt to change it.

v3.0.0 will apply the above change for processing `null` input and will also update the documentation. Please note that this is also a breaking change since the update will only support Node.JS v6 and above. Node 4 is no longer supported due to upstream library changes.

**Comment by TotallyInformation** [comment]
New Version v3.0.0 published.

**Comment by TotallyInformation** [comment]
Thanks to everyone who has commented. Both here and [in the Discourse Group](https://discourse.nodered.org/t/node-red-contrib-moment-breaking-update-looking-for-input/3380).

Consensus seems to be to leave the processing as-is:

Invalid inputs - any input that exists but cannot be converted to a date/time - will result in an empty string as output along with a debug warning message. If the input doesn't exist at all (e.g. you pass a non-existent msg/global/flow property) results in the current date/time being used as input.

Although I forgot to update the docs, you can also use the following convenience strings as input: "today", "yesterday", "tomorrow".
