### ISSUE TITLE
Refresh Timezone settings

### ISSUE THREAD

**Issue by aiwiss** [TotallyInformation/node-red-contrib-moment#16]
Hello,

I have moment node added to my flow and the purpose is that I need it to determine current timezone and output the date and time in the right format and of course timezone.
I am having an issue, that after changing system locale and time zone, to refresh these settings in the node, I have to browse inside it and delete the last determined timezone field and after that it determines the new one which was set up in my system.
My question is, is there a way to refresh these settings without having to browse and edit the flow?
I have tried restarting node-red and restarting the whole system - it didn't help.

Thanks,
Aivaras

**Comment by TotallyInformation** [comment]
Hi Aivaras, not really sure why that is happening. Sounds like a logic failure in the default settings check. I'm afraid I'm about to go on holiday - I will look at it when I get back. If you fancy trying to debug it, please feel free to do a pull request, I might be able to respond to one of those while I'm away.

**Comment by aiwiss** [comment]
Hi,

I have uploaded changes which solves this issue.

Thanks,
Aivaras

**Comment by TotallyInformation** [comment]
Hay aiwiss, you haven't submitted a pull request. Any chance you can so that I can include for everyone else?
