### ISSUE TITLE
Node to convert elapsed time input to formatted output

### ISSUE THREAD

**Issue by TotallyInformation** [TotallyInformation/node-red-contrib-moment#17]
Although the humanize node allows input of seconds - it only converts it to an approximate output.

It would be useful to have a node that could take input in a number of elapsed time formats such as:
- milliseconds
- seconds
- object: `{ 'days': nn, 'hours': nn, 'minutes': nn }`
- etc

and output a formatted elapsed time such as:
- `HH:mm:ss`
- `D days, H hours, m minutes, s seconds`
- etc

**Comment by TotallyInformation** [comment]
Closed for now as it is on my backlog for a future release.

**Comment by k5map** [comment]
@TotallyInformation ... I read this post and have a need for humanize to provide a more accurate output (like when you run CLI command uptime on the RPi).  Do you have any plans to add this feature?

**Comment by TotallyInformation** [comment]
Hi there, thanks for getting in touch. I've really not had time to work on this node at all recently. Really it needs rewriting to use something other than momenjs anyway since that is pretty much a dead project.

Of course, if you have the time and skills to do a PR, please do feel free :-)
