### ISSUE TITLE
unix utc timestamp as input

### ISSUE THREAD

**Issue by Swake001** [TotallyInformation/node-red-contrib-moment#18]
Hi,

Does the node supports a unix utc timestamp as input? (expressed in milliseconds as opposed to a JS timestamp expressed in microseconds). I tried several things but it doesn't seem to accept it or at least I can't find a way to make it understand the unix timestamp other that converting the value prior to injecting it.

2 examples:
1512545487 (this is 2017-12-06T07:31:28.000Z) returns error message: "The input property was NOT a recognizable date. Output will be a blank string"
and
1512574763 (this is 2017-12-06T15:39:23.000Z) returns "1970-01-18T12:09:34.763Z"

Other than that node-red-contrib-moment is a very useful node :-)

Rgds,
Swake

**Comment by TotallyInformation** [comment]
I'm afraid that, currently, the input should be a JavaScript timestamp or a string recognisable by Moment's parser as a date/time.

JavaScript timestamps are actually in milliseconds since 1970-1-1, UNIX timestamps are generally in seconds. So to get the right input to Moment from a UNIX timestamp, simply multiply by 1000.

**Comment by TotallyInformation** [comment]
Here is an example flow with commentary to illustrate the point.

```
[{"id":"df76bbb4.8529e8","type":"inject","z":"533475c4.a28eac","name":"UNIX timestamp","topic":"UNIX timestamp","payload":"1512545487","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":380,"wires":[["c5a8c.dddf4574"]]},{"id":"c5a8c.dddf4574","type":"moment","z":"533475c4.a28eac","name":"","topic":"","input":"","inputType":"msg","inTz":"","adjAmount":0,"adjType":"days","adjDir":"add","format":"","locale":"","output":"","outputType":"msg","outTz":"","x":420,"y":380,"wires":[["e5a3e641.545528"]]},{"id":"e5a3e641.545528","type":"debug","z":"533475c4.a28eac","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":610,"y":380,"wires":[]},{"id":"48c26998.0d90a8","type":"inject","z":"533475c4.a28eac","name":"JS Timestamp","topic":"JS Timestamp","payload":"1512545487000","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":420,"wires":[["c5a8c.dddf4574"]]},{"id":"d12e7985.07ef88","type":"comment","z":"533475c4.a28eac","name":"Expected Output","info":"UNIX Timestamps are the number of **SECONDS** \nsince 1970-01-01 00:00:00.\n\nJavaScript Timestamps are the number of **MILLIseconds**\nsince 1970-01-01 00:00:00.\n\nMoment.JS only recognises JavaScript timestamps\nso if you want to process a UNIX timestamp, \nplease multiply by 1000 as in the second\ninput.","x":400,"y":420,"wires":[]}]
```
