### ISSUE TITLE
Spamming Node-Red console

### ISSUE THREAD

**Issue by Tisonus** [TotallyInformation/node-red-contrib-moment#22]
It would be great if the info log could be disabled. I use a lot of moment nodes, so my debug console gets overcrowded.

I did it myself by deleting the node.log line, but maybe it would be nice to implement a setting to keep the function.

![grafik](https://user-images.githubusercontent.com/35368348/46950185-35b33e80-d084-11e8-84c6-c6d5bc4b777d.png)

**Comment by TotallyInformation** [comment]
Hi, sorry about the delayed response. I wasn't aware that this was logging. I'll need to try and track down where this is happening. Thanks for reporting. I will fix as soon as I can.

**Comment by TotallyInformation** [comment]
OK, log statement removed. Version bumped to v3.0.1 and published to npm. Thanks for your help.
