### ISSUE TITLE
Feature: get number week of the month

### ISSUE THREAD

**Issue by itajackass** [TotallyInformation/node-red-contrib-moment#23]
Is it possible to use default moment methods? I need for example get in output the number of the week of the year

**Comment by TotallyInformation** [comment]
Sorry, I missed this.

If you give the output format as "W", "Wo" (small letter oh, not zero) or "WW", you will get the week of the year as the output.

![image](https://user-images.githubusercontent.com/1591850/58375068-b8697980-7f42-11e9-8d08-7d10c9380c1f.png)

https://momentjs.com/docs/#/displaying/format/
