### ISSUE TITLE
Input to Output changes

### ISSUE THREAD

**Issue by DuncanCT** [TotallyInformation/node-red-contrib-moment#28]
I am trying to convert msg.payload [epoch] to msg.payload.time [date]. Can't seem to get the output to the correct format. Will only output to msg.payload. Have tried all possible combinations. Is this an issue or my incompetence? 

TIA

**Comment by TotallyInformation** [comment]
Hi, sorry I appear to have missed this being opened.

Can you share some example input data and the configuration settings you've tried in moment? I think this should work OK but it is always possible that you've hit an edge-case.

**Comment by TotallyInformation** [comment]
Closed due to inactivity.
