### ISSUE TITLE
Output TZ field from msg.x value

### ISSUE THREAD

**Issue by justinj0001** [TotallyInformation/node-red-contrib-moment#31]
I need to do timezone conversions based on a value that will be passed to the node in a msg.x field.
Data being converted from is all in UTC and the users timezone string (i.e. Australia/Melbourne) from an SQL query will determine the timezone it will convert to.  If I manually set in Output TZ it converts correctly but I need it to be dynamic.
I've tried entering the field as msg.payload.timezone which contains the timezone string but just get the following error as the data is parsed as entered rather than the actual message content.
How do I do what I need to?

> Moment: Output Timezone Invalid, reset to UTC - see http://momentjs.com/timezone/docs/#/data-loading/

**Comment by TotallyInformation** [comment]
Sorry, been a while since I looked at the code. Make take me a bit to get to looking as I'm rather tied up with COVID related issues right now.

**Comment by justinj0001** [comment]
Understandable.  We're all in the same boat.
I've had a brief look and I probably could do a pull and change on it but JS is far from my forte so if someone else versed in JS could have a look it would probably be much smoother.

**Comment by TotallyInformation** [comment]
Good, if rather delayed, news.

From v4 of this node, due to be released imminently, both the input and the output timezones can be set from the input msg.

`msg.inTz` and `msg.outTz` are the two properties to use.
