### ISSUE TITLE
UNIX Timestamp Conversion

### ISSUE THREAD

**Issue by virtualarchitectures** [TotallyInformation/node-red-contrib-moment#32]
I'm using the Date/Time Formatter to convert two differently formatted time stamps.

1. servertime: "2018-06-03T00:30:56.982+01:00" = serverunix: "1527985856982"
2. devicetime: "2018-06-03 00:30:56.678239" = deviceunix: "1529713856678"

The second conversion results in a unix time corresponding to the wrong date: Saturday, June 23, 2018 12:30:56.678 AM.

Could you please clarify if this is user error or an issue with the converter itself?

![image](https://user-images.githubusercontent.com/10799911/81458729-dd76ec80-9193-11ea-9787-448f6646c067.png)

**Comment by TotallyInformation** [comment]
Hi, sorry about the delayed response.

This is a known issue. I tried to get MomentJS to fix it but they declined saying that you shouldn't use so many decimals on seconds - go figure. They are wrong of course, a utility should at least issue a warning if data is out of scope.

There is another closed issue on this #20 and I did think I'd put something into the docs. I thought that I'd tried to filter out errors like that as well but clearly I either dreamt that or couldn't make it work reliably. 

I'm afraid that the only thing you can do right now is to trim the seconds values to 3dp or less.

**Comment by virtualarchitectures** [comment]
Thanks for the confirmation and apologies for missing the prior issue.

**Comment by TotallyInformation** [comment]
No problem.
