### ISSUE TITLE
Add better links to MomentJS documentation

### ISSUE THREAD

**Issue by TotallyInformation** [TotallyInformation/node-red-contrib-moment#34]
This node uses MomentJS to do all the heavy lifting. Both the available formats and the available Timezones come from that package.

While there is a link to the docs in the help sidebar, it might be nice to have an icon/link to the appropriate help information for both the formats inputs and the timezones inputs.

Timezones might have to link back to the GitHub repo for MomentJS, not sure if they are documented elsewhere other than the definition file.

_This would make a great starter task for anyone wanting to help with maintaining/enhancing the moment node._

Thanks to @dceejay for the prompt:

> while we don't encourage it (as it won't work offline) - in this case it may be useful to have a small (i) icon to the right of that field to link direct to that docs page as everyone will need it - and it would shortcut reading the help info.

>Finally likewise the timezones - the info says "check the valid timezone list built in to moment-timezone" - err where / how do I do that ? do you have a link ? (or should it be a select box ?)

**Comment by StephanStS** [comment]
Is the updated documentation with several links to moment.js in my fork (https://github.com/StephanStS/node-red-contrib-moment) a solution?
I put this docu rework into pull request #38.

**Comment by TotallyInformation** [comment]
Incorporated into v4 due to be released shortly & already in master.
