### ISSUE TITLE
Output Format "date" and "jsDate" gives identical output as left open

### ISSUE THREAD

**Issue by StephanStS** [TotallyInformation/node-red-contrib-moment#37]
If you set the configuration property ***Output Format*** to *date* or *jsDate*, the output is always Zulu format.  
I assume that the underlying call *moment().toDate()* shall give a different output format.

**Comment by TotallyInformation** [comment]
using date or jsDate should give the same output, namely ISO8601. That format always outputs in Zulu (AKA UTC or GMT) time as per the standard.

**Comment by TotallyInformation** [comment]
Argh! Node-RED playing tricks on me! The output is not what it seems.

**Comment by TotallyInformation** [comment]
The output for date and jsDate _ARE_ the same - both are JavaScript date objects. My test routine was auto-converting them to ISO format which is the default `.toString` for a JavaScript Date object.

So the outcome you are seeing _is_ the expected outcome.
