### ISSUE TITLE
fromnow in hours or days as number

### ISSUE THREAD

**Issue by Vinisz** [TotallyInformation/node-red-contrib-moment#39]
Hi,

Would it be possible to output "fromnow" just as a number ?
That number can be days (in number) or hours (in number)
That way, I can better process it in a switchnode do display a list of systems not reported in 3 days from now.

**Comment by TotallyInformation** [comment]
Apologies for not responding sooner. This node is really "functionally stabilised" now and isn't likely to get enhancements unless someone can spare some time to do so. The moment.js library is now also available via JSONata so you can use the change node and other nodes that accept JSONata (including the function node) to do date/time processing.
