### ISSUE TITLE
US first day of the week

### ISSUE THREAD

**Issue by alexsahka** [TotallyInformation/node-red-contrib-moment#40]
![image](https://user-images.githubusercontent.com/7469537/102849626-6150b280-43cc-11eb-9889-34319eeaf756.png)
Us week starting on Sunday, not Monday
When selecting:
en_US
America/Los_Angeles

Week changing on Monday.
![image](https://user-images.githubusercontent.com/7469537/102849828-d45a2900-43cc-11eb-997e-2ad9d801e0c7.png)

**Comment by TotallyInformation** [comment]
Unfortunately, all processing of dates happens via the moment.js library. So if there are issues, it is with that library I'm afraid. The moment node really needs a full rewrite to use a more currently library but I don't have time to do that right now.
