### ISSUE TITLE
Not an issue but a request - Adjustment value using a flow or global variable

### ISSUE THREAD

**Issue by cdk222** [TotallyInformation/node-red-contrib-moment#41]
Hi - not sure where to enter a change request in github so I have opened an issue.

Would it be possible to alter the adjustment section of the node so it allows flow or global variables to be used as the adjustment amount. If you can I have not been able to find the syntax to call a flow or global variable within the adjustment text box. I have been able to get it working by calling an environmental variable however this really doesn't suit a purpose as you can not manipulate the environmental variable within a flow.

Anyway any help or change would be appreciated. thanks

**Comment by TotallyInformation** [comment]
Hi, you should use a change node before this node to move the data to the correct property.

`msg.adjAmount` - should contain the amount to adjust.
`msg.adjType` - should contain either "subtract" or "add".
