### ISSUE TITLE
Possible to convert "Week of Year" to Date

### ISSUE THREAD

**Issue by paede81** [TotallyInformation/node-red-contrib-moment#49]
Hi

Is it possible to convert "Week of Year" to a date? I have to find the first day of a week. Example: Week 21 should get 22.05.2023

Regards,
Patrick

**Comment by TotallyInformation** [comment]
Hi, not sure about in this particular node. However, Moment is now also built into JSONata so you may be able to translate [this answer on StackOverflow](https://stackoverflow.com/questions/18985475/generate-date-from-week-number-in-moment-js) to JSONata.

**Comment by TotallyInformation** [comment]
You can do this with raw moment.js: https://momentjs.com/docs/#/manipulating/start-of/

So it should work in JSONata. You can't do it with this node I'm afraid.
