### ISSUE TITLE
Please use RED.util.getMessageProperty & RED.util.setMessageProperty

### ISSUE THREAD

**Issue by mikeS7** [TotallyInformation/node-red-contrib-moment#6]
Can't use properties like payload.timestamp for input and output ...

please change lines 88 and 260 to:
inp = RED.util.getMessageProperty(msg, node.input);

and

RED.util.setMessageProperty(msg, output, value);

**Comment by TotallyInformation** [comment]
Thanks Mike. I will update as soon as I can.

**Comment by TotallyInformation** [comment]
Committed to master
